
export const LANGUAGES: Record<string, any> = {
  en: {
    menu: {
      file: "File",
      file_open: "Open File...",
      file_recent: "Recent Files",
      file_exit: "Exit",
      playback: "Playback",
      playback_play_pause: "Play/Pause",
      playback_stop: "Stop",
      playback_previous: "Previous",
      playback_next: "Next",
      playback_speed: "Speed",
      audio: "Audio",
      audio_tracks: "Audio Tracks",
      audio_mute: "Mute",
      audio_equalizer: "Equalizer...",
      video: "Video",
      video_aspect_ratio: "Aspect Ratio",
      video_fullscreen: "Fullscreen",
      subtitles: "Subtitles",
      subtitles_load: "Load Subtitle File...",
      playlist: "Playlist",
      playlist_show: "Show Playlist",
      tools: "Tools",
      tools_media_info: "Media Information",
      tools_preferences: "Preferences...",
      view: "View",
      view_themes: "Themes",
      help: "Help",
      help_about: "About KNOX Player X..."
    },
    controls: {
      play: "Play",
      pause: "Pause",
      stop: "Stop",
      previous: "Previous",
      next: "Next",
      volume: "Volume",
      seek: "Seek",
      mute: "Mute",
      unmute: "Unmute",
      fullscreen: "Fullscreen",
      speed: "Playback Speed"
    },
    panels: {
      audio_title: "Audio Engine",
      video_title: "Video Engine",
      subtitle_title: "Subtitle Engine",
      playlist_title: "Library",
      info_title: "Diagnostics",
      audio_volume: "Master Volume",
      audio_equalizer: "DSP Equalizer",
      video_brightness: "Brightness",
      video_contrast: "Contrast",
      video_deinterlace: "Deinterlacing",
      video_reset_filters: "Reset Filters",
      subtitle_font: "Font Family",
      subtitle_size: "Size",
      subtitle_color: "Color",
      info_codec: "Codec",
      info_resolution: "Resolution",
      info_performance: "Engine Flow"
    },
    settings: {
      title: "Settings Console",
      appearance: "Appearance",
      performance: "Engine",
      audio: "Audio",
      video: "Video",
      subtitles: "Subtitles",
      shortcuts: "Keymap",
      advanced: "Native",
      apply: "Commit Changes",
      cancel: "Discard",
      ok: "OK"
    },
    messages: {
      loading: "Initializing HW Pipeline...",
      error: "Critical Engine Failure",
      buffering: "Buffering Stream..."
    }
  },
  ar: {
    menu: {
      file: "ملف",
      file_open: "فتح ملف...",
      file_recent: "الملفات الأخيرة",
      file_exit: "خروج",
      playback: "التشغيل",
      playback_play_pause: "تشغيل/إيقاف مؤقت",
      playback_stop: "إيقاف",
      playback_previous: "السابق",
      playback_next: "التالي",
      playback_speed: "سرعة التشغيل",
      audio: "الصوت",
      audio_tracks: "مسارات الصوت",
      audio_mute: "كتم الصوت",
      audio_equalizer: "المعادل...",
      video: "الفيديو",
      video_aspect_ratio: "نسبة العرض للارتفاع",
      video_fullscreen: "ملء الشاشة",
      subtitles: "الترجمة",
      subtitles_load: "تحميل ملف ترجمة...",
      playlist: "قائمة التشغيل",
      playlist_show: "عرض قائمة التشغيل",
      tools: "أدوات",
      tools_media_info: "معلومات الوسائط",
      tools_preferences: "التفضيلات...",
      view: "عرض",
      view_themes: "السمات",
      help: "مساعدة",
      help_about: "حول KNOX Player X..."
    },
    controls: {
      play: "تشغيل",
      pause: "إيقاف مؤقت",
      stop: "إيقاف",
      previous: "السابق",
      next: "التالي",
      volume: "الصوت",
      seek: "البحث",
      mute: "كتم",
      unmute: "إلغاء الكتم",
      fullscreen: "ملء الشاشة",
      speed: "سرعة التشغيل"
    },
    panels: {
      audio_title: "محرك الصوت",
      video_title: "محرك الفيديو",
      subtitle_title: "محرك الترجمة",
      playlist_title: "المكتبة",
      info_title: "التشخيص",
      audio_volume: "الصوت الرئيسي",
      audio_equalizer: "المعادل الرقمي",
      video_brightness: "السطوع",
      video_contrast: "التباين",
      video_deinterlace: "إزالة التشابك",
      video_reset_filters: "إعادة ضبط المرشحات",
      subtitle_font: "نوع الخط",
      subtitle_size: "الحجم",
      subtitle_color: "اللون",
      info_codec: "الترميز",
      info_resolution: "الدقة",
      info_performance: "تدفق المحرك"
    },
    settings: {
      title: "لوحة التحكم",
      appearance: "المظهر",
      performance: "المحرك",
      audio: "الصوت",
      video: "الفيديو",
      subtitles: "الترجمة",
      shortcuts: "الاختصارات",
      advanced: "متقدم",
      apply: "حفظ التغييرات",
      cancel: "إلغاء",
      ok: "موافق"
    },
    messages: {
      loading: "جارٍ تهيئة خط معالجة العتاد...",
      error: "فشل حرج في المحرك",
      buffering: "جارٍ تحميل البث..."
    }
  }
};
