// KNOUX Player X — File generated by automated export
// Author: knoux (أبو ريتاج) — KNOUX Player X

export { default as neonPurple } from './neonPurple';
export { default as neonCyan } from './neonCyan';
