// KNOUX Player X — File generated by automated export
// Author: knoux (أبو ريتاج) — KNOUX Player X

const neonCyan = { name: 'neonCyan', primary: '#06B6D4', accent: '#7C3AED', glow: '#67E8F9' };
export default neonCyan;
